---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hadoop.
--- DateTime: 2019/5/23 10:07
---

--- String 类型枚举，保存最近 10 条数据， score 为 time
local key = KEYS[1];
local score = tonumber(ARGV[1]);
local value = ARGV[2];
local maxNum = tonumber(ARGV[3]);
redis.call('ZADD', key, score, value);
local num = tonumber(redis.call('ZCARD', key));
if num > maxNum then
    redis.call('ZREMRANGEBYRANK', key, 0, num - maxNum - 1);
end


--- 数值类型保存最大最小值
--- hmget hgetall 都是返回 array 类型
local key = KEYS[1];
local value = tonumber(ARGV[1]);
local hash = redis.call('HMGET', key, 'max', 'min');
if hash and next(hash) then
    local max = hash[1];
    local min = hash[2];
    if max == false or value > tonumber(max) then
        redis.call('HSET', key, 'max', value)
    end
    if min == false or value < tonumber(min) then
        redis.call('HSET', key, 'min', value)
    end
else
    redis.call('HMSET', key, 'max', value, 'min', value);
end
